Default: &defaults
  user: heroku
  password: herokupass
  host: ds033047.mongolab.com
  port: 33047
  database: heroku_app4217373
  poolsize: 1

Development:
  <<: *defaults

Testing:
  database: Exodus_test
  <<: *defaults

Staging:
  <<: *defaults
 
Production:
  <<: *defaults
