Default: &defaults
  user: Exodus
  password: Exodus
  host: localhost
  port: 27017
  database: Exodus
  poolsize: 1

Development:
  <<: *defaults

Testing:
  database: Exodus_test
  <<: *defaults

Staging:
  <<: *defaults
 
Production:
  <<: *defaults
