Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  copyright: "copyright"
  approot: "http://localhost:3000"
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  approot: "http://50.116.22.52:8080"
  port: 8080
  <<: *defaults

Production:
  approot: "http://50.116.22.52"
  port: 80
  <<: *defaults
